### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by akaszynski** [mechajeff/marketing#2]
- Slide 1 (really wanted to say zero)
  - Should use large text for authors, etc.
  - Date (year) needs to be corrected.
- Slide 3
  - Could use smooth_shading=True for target cad.  Right-hand side appears shifted lower.
- Slide 5
  - Nice work with the videos.  However, this won't play unless the videos are packaged with the pdf.  Evince is looking for `figures/disk_side.mp4` see the error message:
```
(evince:110468): EvinceView-WARNING **: 10:59:41.554: Error: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure. (gstbasesrc.c(3468): gst_base_src_start (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin0/GstFileSrc:source:
Failed to start)
```
- Slide 7
  - Consider using the femorph icon
  https://avatars.githubusercontent.com/u/53436066?s=200&v=4

- Slide 19 & Slide 20
  - Having the following statements on back-to-back slides seems redundant.  If there was more slide spacing it wouldn't matter.
    - "Utilized by large P&W user base for wide range of applications"
    - "Used extensivey by P&W in many applications"  <-- NOTE: "extensivey" spelled wrong
  - Looking at 18 more, I realize that it might need more work in regards to our testing, pipeline, deployment, CI/CD, etc.  Non-software people won't get it, but may be a cool picture of an azure pipeline or some software programmer aggressively drinking coffee would get the point across.

**Comment by mechajeff** [comment]
Updates updated.  Have a look.  Still a draft version.
